export const CANDIDATES_CAPTURE_DATE = "2026-06-10";

const SOURCE = "Yahoo Finance quoteSummary/key-statistics";
const SOURCE_DATE = CANDIDATES_CAPTURE_DATE;

const candidateSnapshots = [
  {
    ticker: "LEN",
    companyName: "Lennar",
    sector: "Residential Construction",
    price: 90.9,
    pe: 13.06,
    pb: 1.02,
    pePb: 13.27,
    debtRatio: 0.51,
    currentRatio: 8.32,
    quickRatio: 4.51,
    fcf: 365.79,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Perfil Graham limpio: P/B cercano a 1, deuda moderada y liquidez muy amplia. Riesgo principal: concentracion ciclica en vivienda.",
  },
  {
    ticker: "KBH",
    companyName: "KB Home",
    sector: "Residential Construction",
    price: 51.45,
    pe: 9.93,
    pb: 0.84,
    pePb: 8.3,
    debtRatio: 0.74,
    currentRatio: 2.2,
    quickRatio: 0.2,
    fcf: 475.53,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "La mas barata del grupo por P/E x P/B, pero quick ratio muy bajo por inventario. Aprobada por Graham defensivo, con riesgo operativo de ciclo e inventario.",
  },
  {
    ticker: "CEG",
    companyName: "Constellation Energy",
    sector: "Utilities / Nuclear AI Infrastructure",
    price: 251.65,
    pe: 21.86,
    pb: 2.72,
    pePb: 59.54,
    debtRatio: 0.66,
    currentRatio: 1.36,
    quickRatio: 0.48,
    fcf: -4478.88,
    epsAllPositive: false,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Utility nuclear con exposicion directa a demanda electrica de data centers. Calidad estrategica alta, pero Graham exige cautela por P/B elevado y FCF negativo.",
  },
  {
    ticker: "VST",
    companyName: "Vistra",
    sector: "Utilities / Power Generation",
    price: 146.22,
    pe: 24.45,
    pb: 18.86,
    pePb: 461.15,
    debtRatio: 3.55,
    currentRatio: 0.9,
    quickRatio: 0.26,
    fcf: 476.88,
    epsAllPositive: false,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Generacion electrica ligada a demanda de energia para AI. Sigue en radar, pero no es compra Graham defensiva por deuda, liquidez y P/B muy altos.",
  },
  {
    ticker: "ETR",
    companyName: "Entergy",
    sector: "Utilities / Regulated Electric",
    price: 109.66,
    pe: 27.97,
    pb: 2.89,
    pePb: 80.96,
    debtRatio: 1.93,
    currentRatio: 0.96,
    quickRatio: 0.61,
    fcf: -3913.1,
    epsAllPositive: null,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Utility regulada con exposicion al sur de EE.UU. y carga electrica industrial. La tesis es infraestructura, no aprobacion Graham: FCF negativo y deuda alta.",
  },
  {
    ticker: "HUBB",
    companyName: "Hubbell",
    sector: "Industrials / Electrical Equipment",
    price: 486.47,
    pe: 28.73,
    pb: 6.82,
    pePb: 196.0,
    debtRatio: 0.72,
    currentRatio: 1.58,
    quickRatio: 0.84,
    fcf: 541.45,
    epsAllPositive: null,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Infraestructura electrica para redes, electrificacion y data centers. Empresa de calidad, aunque fuera del rango defensivo Graham por valuacion.",
  },
  {
    ticker: "INGR",
    companyName: "Ingredion",
    sector: "Consumer Defensive / Packaged Foods",
    price: 101.64,
    pe: 9.77,
    pb: 1.46,
    pePb: 14.28,
    debtRatio: 0.41,
    currentRatio: 2.76,
    quickRatio: 1.78,
    fcf: 357.75,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Defensiva de ingredientes y alimentos con P/E bajo, P/B razonable, deuda controlada y liquidez superior a 2. Es la candidata Graham mas limpia del grupo.",
  },
  {
    ticker: "PFE",
    companyName: "Pfizer",
    sector: "Healthcare / Pharmaceuticals",
    price: 25.7,
    pe: 19.62,
    pb: 1.63,
    pePb: 31.89,
    debtRatio: 0.72,
    currentRatio: 1.25,
    quickRatio: 0.85,
    fcf: 12376.63,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Farmaceutica grande con FCF positivo y P/E bajo 20. No pasa Graham estricta por liquidez menor a 2 y P/E x P/B sobre 22.5.",
  },
  {
    ticker: "GIS",
    companyName: "General Mills",
    sector: "Consumer Defensive / Packaged Foods",
    price: 33.72,
    pe: 8.24,
    pb: 3.26,
    pePb: 26.85,
    debtRatio: 2.18,
    currentRatio: 0.56,
    quickRatio: 0.3,
    fcf: 2263.38,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Consumo defensivo con P/E bajo y FCF positivo. Se mantiene en observacion por deuda alta, liquidez baja y P/B mayor al limite defensivo.",
  },
  {
    ticker: "REGN",
    companyName: "Regeneron Pharmaceuticals",
    sector: "Healthcare / Biotechnology",
    price: 616.18,
    pe: 15.04,
    pb: 2.0,
    pePb: 30.06,
    debtRatio: 0.09,
    currentRatio: 3.57,
    quickRatio: 2.84,
    fcf: 3273.35,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Salud rentable con balance muy fuerte, liquidez amplia y FCF positivo. Queda cerca, pero P/E x P/B supera el umbral 22.5.",
  },
  {
    ticker: "BAC",
    companyName: "Bank of America",
    sector: "Financial Services / Banks",
    price: 54.42,
    pe: 13.5,
    pb: 1.41,
    pePb: 19.01,
    debtRatio: null,
    currentRatio: null,
    quickRatio: null,
    fcf: null,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Banco diversificado con P/B menor a 1.5 y ROE sobre 10%. En financieras los ratios current/quick/debt no son comparables con industriales.",
  },
  {
    ticker: "USB",
    companyName: "U.S. Bancorp",
    sector: "Financial Services / Banking",
    price: 55.52,
    pe: 12.05,
    pb: 1.48,
    pePb: 17.83,
    debtRatio: null,
    currentRatio: null,
    quickRatio: null,
    fcf: null,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Banco regional con valuacion moderada y largo historial de dividendos. P/E x P/B dentro del umbral Graham para financieras. Metricas industriales no aplican.",
  },
  {
    ticker: "CFG",
    companyName: "Citizens Financial Group",
    sector: "Financial Services / Banking",
    price: 63.78,
    pe: 16.35,
    pb: 1.11,
    pePb: 18.15,
    debtRatio: null,
    currentRatio: null,
    quickRatio: null,
    fcf: null,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Banco regional con P/B menor a 1.2 y P/E x P/B dentro del rango Graham. Menor capitalizacion que los grandes; mas sensible a ciclos crediticios.",
  },
  {
    ticker: "TRV",
    companyName: "The Travelers Companies",
    sector: "Financial Services / Insurance",
    price: 299.6,
    pe: 8.58,
    pb: 1.99,
    pePb: 17.07,
    debtRatio: null,
    currentRatio: null,
    quickRatio: null,
    fcf: null,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Aseguradora P&C con P/E bajo y P/B cerca del limite 2. Pasa la regla 22.5 con margen. Clave evaluar siniestralidad y ROE; metricas industriales no aplican.",
  },
  {
    ticker: "PRU",
    companyName: "Prudential Financial",
    sector: "Financial Services / Insurance",
    price: 103.7,
    pe: 10.68,
    pb: 1.13,
    pePb: 12.03,
    debtRatio: null,
    currentRatio: null,
    quickRatio: null,
    fcf: 10379.0,
    epsAllPositive: null,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Aseguradora con P/B bajo, ROE cercano a criterio y FCF positivo. Requiere lectura financiera especifica antes de compararla contra industriales.",
  },
  {
    ticker: "QCOM",
    companyName: "QUALCOMM",
    sector: "Technology / Semiconductors",
    price: 205.42,
    pe: 22.09,
    pb: 7.97,
    pePb: 176.15,
    debtRatio: 0.56,
    currentRatio: 2.37,
    quickRatio: 1.45,
    fcf: 9589.62,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Tecnologia rentable, FCF fuerte y liquidez suficiente. Es razonable frente a growth puro, pero no Graham por P/B elevado.",
  },
  {
    ticker: "CTSH",
    companyName: "Cognizant Technology Solutions",
    sector: "Technology / IT Services",
    price: 52.94,
    pe: 11.48,
    pb: 1.67,
    pePb: 19.12,
    debtRatio: 0.07,
    currentRatio: 2.23,
    quickRatio: 1.74,
    fcf: 1908.88,
    epsAllPositive: true,
    source: SOURCE,
    sourceDate: SOURCE_DATE,
    note: "Tecnologia no especulativa: P/E bajo, liquidez fuerte, deuda minima y FCF positivo. Cumple gran parte del perfil defensivo.",
  },
  {
    ticker: "ORCL",
    companyName: "Oracle Corporation",
    sector: "Technology / Software Infrastructure",
    price: 212.08,
    pe: 38.01,
    pb: 18.18,
    pePb: 690.91,
    debtRatio: 7.21,
    currentRatio: 0.75,
    quickRatio: 0.75,
    fcf: -890,
    epsAllPositive: true,
    epsGrowing: true,
    source: "Yahoo Finance fundamentalsTimeSeries + FX",
    sourceDate: "2025-05-31",
    note: "Software de base de datos y nube empresarial. EPS creciente y positivo, pero rechazada Graham: P/E 38, P/B 18 (P/E x P/B ~691), deuda elevada (7.2x patrimonio), liquidez inferior a 1 y FCF negativo. Perfil de crecimiento, no defensivo.",
  },
];

export const grahamCandidates = candidateSnapshots.map((candidate) => ({
  ...candidate,
  captureDate: candidate.captureDate || CANDIDATES_CAPTURE_DATE,
}));
