export const CANDIDATES_CAPTURE_DATE = "2026-06-03";

const candidateSnapshots = [
  {
    ticker: "PHM",
    companyName: "PulteGroup",
    sector: "Residential Construction",
    price: 117.77,
    pe: 11.39,
    pb: 1.75,
    pePb: 19.89,
    debtRatio: 0.4,
    currentRatio: 6.24,
    quickRatio: 0.94,
    fcf: 1831.38,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Constructor grande con valuacion dentro del limite 22.5 y liquidez alta; quick ratio bajo por inventario de vivienda, normal en el sector pero relevante para Graham.",
  },
  {
    ticker: "LEN",
    companyName: "Lennar",
    sector: "Residential Construction",
    price: 90.9,
    pe: 13.06,
    pb: 1.02,
    pePb: 13.27,
    debtRatio: 0.51,
    currentRatio: 8.32,
    quickRatio: 4.51,
    fcf: 365.79,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Perfil Graham limpio: P/B cercano a 1, deuda moderada y liquidez muy amplia. Riesgo principal: concentracion ciclica en vivienda.",
  },
  {
    ticker: "TOL",
    companyName: "Toll Brothers",
    sector: "Residential Construction",
    price: 139.53,
    pe: 10.55,
    pb: 1.54,
    pePb: 16.25,
    debtRatio: 0.71,
    currentRatio: 3.09,
    quickRatio: 0.45,
    fcf: 1332.53,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Valuacion atractiva y FCF positivo; quick ratio bajo porque el balance depende de inventarios/lotes. Requiere cuidado con ciclo inmobiliario.",
  },
  {
    ticker: "TMHC",
    companyName: "Taylor Morrison Home",
    sector: "Residential Construction",
    price: 71.5,
    pe: 10.67,
    pb: 1.08,
    pePb: 11.54,
    debtRatio: 0.56,
    currentRatio: 7.51,
    quickRatio: 1.45,
    fcf: 601.88,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Muy barata por P/E x P/B y con liquidez robusta. Mejor balance de liquidez que varias constructoras por quick ratio sobre 1.",
  },
  {
    ticker: "MTH",
    companyName: "Meritage Homes",
    sector: "Residential Construction",
    price: 68.12,
    pe: 12.5,
    pb: 0.89,
    pePb: 11.15,
    debtRatio: 0.48,
    currentRatio: 10.96,
    quickRatio: 1.6,
    fcf: 208.15,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Cotiza bajo book value y conserva liquidez fuerte. Buen candidato Graham, aunque dependiente del ciclo de tasas/vivienda.",
  },
  {
    ticker: "CTSH",
    companyName: "Cognizant Technology Solutions",
    sector: "IT Services",
    price: 55.14,
    pe: 11.99,
    pb: 1.73,
    pePb: 20.79,
    debtRatio: 0.36,
    currentRatio: 2.23,
    quickRatio: 2.23,
    fcf: 1728,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "No es constructora: servicios IT con liquidez real, deuda baja y FCF positivo. P/E x P/B pasa, pero esta mas cerca del limite 22.5.",
  },
  {
    ticker: "INGR",
    companyName: "Ingredion",
    sector: "Packaged Foods",
    price: 101.12,
    pe: 9.74,
    pb: 1.45,
    pePb: 14.09,
    debtRatio: 0.79,
    currentRatio: 2.76,
    quickRatio: 1.83,
    fcf: 446,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Defensiva de alimentos empaquetados, menos ciclica que homebuilders. Deuda bajo 1, liquidez suficiente y valuacion Graham razonable.",
  },
  {
    ticker: "MHO",
    companyName: "M/I Homes",
    sector: "Residential Construction",
    price: 138.43,
    pe: 10.42,
    pb: 1.11,
    pePb: 11.57,
    debtRatio: 0.5,
    currentRatio: 7.64,
    quickRatio: 1.78,
    fcf: 156.5,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Pasa con mucho margen la regla 22.5 y mantiene liquidez alta. Empresa mas pequena: revisar volumen, geografias y sensibilidad al inventario.",
  },
  {
    ticker: "KBH",
    companyName: "KB Home",
    sector: "Residential Construction",
    price: 51.45,
    pe: 9.93,
    pb: 0.84,
    pePb: 8.3,
    debtRatio: 0.74,
    currentRatio: 2.2,
    quickRatio: 0.2,
    fcf: 475.53,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "La mas barata del grupo por P/E x P/B, pero quick ratio muy bajo por inventario. Aprobada por Graham defensivo, con riesgo operativo de ciclo e inventario.",
  },
  {
    ticker: "GRBK",
    companyName: "Green Brick Partners",
    sector: "Residential Construction",
    price: 69.02,
    pe: 10.16,
    pb: 1.5,
    pePb: 15.26,
    debtRatio: 0.27,
    currentRatio: 8.45,
    quickRatio: 0.83,
    fcf: 164.48,
    epsAllPositive: true,
    source: "Finviz + StockAnalysis",
    sourceDate: "2026-06-03",
    note: "Deuda muy baja y current ratio amplio. Quick ratio bajo por inventario; aun asi pasa la regla Graham por margen razonable.",
  },
];

export const grahamCandidates = candidateSnapshots.map((candidate) => ({
  ...candidate,
  captureDate: candidate.captureDate || CANDIDATES_CAPTURE_DATE,
}));
