CREATE TABLE IF NOT EXISTS companies (
  ticker TEXT PRIMARY KEY,
  yahoo_symbol TEXT,
  company_name TEXT NOT NULL,
  exchange TEXT,
  market TEXT,
  country TEXT,
  currency TEXT,
  quote_type TEXT DEFAULT 'EQUITY',
  sector TEXT,
  industry TEXT,
  source TEXT,
  source_date TEXT,
  analysis_status TEXT DEFAULT 'pending_fundamentals',
  validation_status TEXT DEFAULT 'needs_manual_review',
  tags TEXT DEFAULT '[]',
  notes TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS financial_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL REFERENCES companies(ticker) ON DELETE CASCADE,
  snapshot_date TEXT NOT NULL,
  price NUMERIC,
  pe NUMERIC,
  pb NUMERIC,
  pe_pb NUMERIC,
  debt_ratio NUMERIC,
  current_ratio NUMERIC,
  quick_ratio NUMERIC,
  fcf NUMERIC,
  eps_all_positive BOOLEAN,
  eps_growing BOOLEAN,
  classification_id TEXT,
  classification_label TEXT,
  source TEXT,
  notes TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ticker, snapshot_date, source)
);

CREATE TABLE IF NOT EXISTS price_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL REFERENCES companies(ticker) ON DELETE CASCADE,
  yahoo_symbol TEXT,
  price NUMERIC NOT NULL,
  currency TEXT,
  source TEXT,
  market_time TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_file TEXT,
  imported_count INTEGER DEFAULT 0,
  skipped_count INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_quality (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL REFERENCES companies(ticker) ON DELETE CASCADE,
  check_name TEXT NOT NULL,
  status TEXT NOT NULL,
  message TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
